 tema: 2. Getting Started; Subtemas: 2.3 Designing algorithms.
Diseñar algoritmos es una de las tareas centrales en la ciencia de la computación. Esta sección introduce el proceso general de creación de algoritmos efectivos, destacando que se trata de mucho más que simplemente escribir código. El primer paso esencial es entender profundamente el problema que se desea resolver. Esto implica identificar claramente la entrada esperada, las restricciones impuestas por el problema y la salida deseada. Una comprensión incorrecta del problema puede llevar al diseño de algoritmos que, aunque funcionen técnicamente, no resuelvan correctamente la situación planteada.

Una vez comprendido el problema, el diseño de algoritmos suele proceder de manera incremental. Es común comenzar con una versión simplificada del problema, resolverla, y luego ir añadiendo complejidad para abarcar el caso general. Esta estrategia permite identificar y solucionar dificultades de forma progresiva, lo que mejora la claridad del diseño y facilita su corrección.

En cuanto a las estrategias de diseño, existen técnicas ampliamente utilizadas que ayudan a abordar una amplia variedad de problemas. Entre ellas, se destacan los enfoques de divide y vencerás, donde el problema se divide en subproblemas más pequeños que se resuelven de forma recursiva; los algoritmos voraces, que toman decisiones locales óptimas esperando encontrar una solución global óptima; la programación dinámica, que resuelve subproblemas superpuestos y almacena sus soluciones; y los algoritmos probabilísticos, que incluyen elementos aleatorios en sus decisiones.

Además del diseño, es fundamental demostrar que el algoritmo es correcto, es decir, que produce la salida adecuada para cualquier entrada válida. Para ello, los diseñadores suelen apoyarse en técnicas como la inducción matemática y el uso de invariantes de bucle, que permiten verificar que cada paso del algoritmo preserva ciertas propiedades que conducen a la solución correcta.

Finalmente, el rendimiento del algoritmo se evalúa con un análisis de complejidad temporal y espacial, que mide cuánto tiempo y cuánta memoria requiere. Esto permite comparar diferentes algoritmos y seleccionar el más adecuado para una situación dada. El proceso de diseño rara vez es lineal; suele ser iterativo. Se prueba un enfoque, se analizan sus resultados, y si no es eficiente o correcto, se ajusta o se rediseña completamente.
